spring.application.name=facturation
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/Okayo
spring.datasource.username=postgres
spring.datasource.password=&Mariamediak5
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect